insert into CATALOG  (PRODUCT_ID  , PRODUCT_NAME  , STOCK  , UNIT_PRICE )
        values('CATALOG-001','Berlin',100,1500);
insert into CATALOG  (PRODUCT_ID , PRODUCT_NAME  , STOCK  , UNIT_PRICE )
values('CATALOG-002','Tokyo',200,2000);
insert into CATALOG  (PRODUCT_ID , PRODUCT_NAME  , STOCK  , UNIT_PRICE )
values('CATALOG-003','Korea',300,2500);